<font color="Blue" size="6">Python Learning 4th Week</font>

Week 4 – Python with NumPy & Pandas

Concepts Covered
1. Introduction to NumPy

NumPy ek Python library hai jo arrays (multi-dimensional data) ke saath fast mathematical operations ke liye use hoti hai.

Normal Python list me operations slow hote hai.

NumPy arrays memory efficient aur fast hote hai.

In [2]:
import numpy as np

# Normal Python list
py_list = [1, 2, 3, 4, 5]
print("Python List:", py_list)

# NumPy array
np_array = np.array([1, 2, 3, 4, 5])
print("NumPy Array:", np_array)


Python List: [1, 2, 3, 4, 5]
NumPy Array: [1 2 3 4 5]


Creating Arrays, Indexing & Slicing

In [3]:
import numpy as np

# 1D array
arr1 = np.array([10, 20, 30, 40, 50])

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Indexing
print("First element:", arr1[0])   # 10
print("Last element:", arr1[-1])  # 50

# Slicing
print("Slice:", arr1[1:4])        # [20 30 40]

# 2D array indexing
print("Element at row 1 col 2:", arr2[0, 1])  # 2


First element: 10
Last element: 50
Slice: [20 30 40]
Element at row 1 col 2: 2


Introduction to Pandas

Pandas ek Python library hai jo tabular data (Excel/CSV jaise) ke liye use hoti hai.
Main structures:

Series → 1D labeled array

DataFrame → 2D table

In [8]:
import pandas as pd

# Create dummy data
data = {
    "Name": ["Tushar", "Aman", "Riya"],
    "Age": [23, 25, 22],
    "City": ["Rohtak", "Delhi", "Mumbai"]
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Save as CSV
df.to_csv("data.csv", index=False)

print("data.csv file created successfully!")


data.csv file created successfully!


Data Import/Export (CSV, Excel)

In [9]:
# Load CSV
df = pd.read_csv("data.csv")

# Export to CSV
df.to_csv("output.csv", index=False)

# Load Excel (if openpyxl installed)
# df = pd.read_excel("data.xlsx")


In [10]:
# Load CSV
df = pd.read_csv("data.csv")

# Export to CSV
df.to_csv("output.csv", index=False)

# Load Excel (if openpyxl installed)
# df = pd.read_excel("data.xlsx")


Basic Data Cleaning (dropna, fillna)

In [11]:
data = {
    "Name": ["Amit", "Rohit", "Sneha", "Priya"],
    "Age": [25, None, 22, None],
    "City": ["Delhi", "Mumbai", None, "Pune"]
}
df = pd.DataFrame(data)

print("Original:\n", df)

# Drop rows with NaN
print("After dropna:\n", df.dropna())

# Fill missing values
print("After fillna:\n", df.fillna({"Age": 0, "City": "Unknown"}))


Original:
     Name   Age    City
0   Amit  25.0   Delhi
1  Rohit   NaN  Mumbai
2  Sneha  22.0    None
3  Priya   NaN    Pune
After dropna:
    Name   Age   City
0  Amit  25.0  Delhi
After fillna:
     Name   Age     City
0   Amit  25.0    Delhi
1  Rohit   0.0   Mumbai
2  Sneha  22.0  Unknown
3  Priya   0.0     Pune


Filtering & Sorting Data

In [12]:
# Filtering
print("Age > 23:\n", df[df["Age"] > 23])

# Sorting
print("Sorted by Age:\n", df.sort_values("Age", ascending=True))


Age > 23:
    Name   Age   City
0  Amit  25.0  Delhi
Sorted by Age:
     Name   Age    City
2  Sneha  22.0    None
0   Amit  25.0   Delhi
1  Rohit   NaN  Mumbai
3  Priya   NaN    Pune


Practice Programs
1. Create a NumPy array and perform basic operations

In [13]:
arr = np.array([5, 10, 15, 20, 25])
print("Array:", arr)
print("Sum:", np.sum(arr))
print("Product:", np.prod(arr))


Array: [ 5 10 15 20 25]
Sum: 75
Product: 375000


2. Find mean, max, min, and reshape arrays

In [14]:
arr = np.arange(1, 13)  # 1 to 12
print("Array:", arr)

print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))

reshaped = arr.reshape(3, 4)
print("Reshaped 3x4:\n", reshaped)


Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Mean: 6.5
Max: 12
Min: 1
Reshaped 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


3. Load a CSV file into Pandas DataFrame

In [16]:
import pandas as pd

# Data create
data = {
    "Name": ["Tushar", "Aman", "Riya"],
    "Age": [23, 25, 22],
    "City": ["Rohtak", "Delhi", "Mumbai"]
}

# DataFrame bana ke CSV save karo
df = pd.DataFrame(data)
df.to_csv("sample.csv", index=False)

print("sample.csv created successfully!")


sample.csv created successfully!


In [17]:
df = pd.read_csv("sample.csv")
print(df)


     Name  Age    City
0  Tushar   23  Rohtak
1    Aman   25   Delhi
2    Riya   22  Mumbai


4. Perform filtering and sorting on dataset

In [20]:
data = {
    "Name": ["Amit", "Rohit", "Sneha", "Priya"],
    "Age": [25, 30, 22, 28],
    "City": ["Delhi", "Mumbai", "Pune", "Delhi"]
}
df = pd.DataFrame(data)

print("Filter Age > 25:\n", df[df["Age"] > 25])
print("Sorted by Name:\n", df.sort_values("Name"))


Filter Age > 25:
     Name  Age    City
1  Rohit   30  Mumbai
3  Priya   28   Delhi
Sorted by Name:
     Name  Age    City
0   Amit   25   Delhi
3  Priya   28   Delhi
1  Rohit   30  Mumbai
2  Sneha   22    Pune


5. Handle missing values in DataFrame

In [21]:
data = {
    "Name": ["Amit", "Rohit", "Sneha", "Priya"],
    "Age": [25, None, 22, None],
    "City": ["Delhi", "Mumbai", None, "Pune"]
}
df = pd.DataFrame(data)

print("Original:\n", df)

# Fill missing values
df_clean = df.fillna({"Age": df["Age"].mean(), "City": "Unknown"})
print("Cleaned:\n", df_clean)


Original:
     Name   Age    City
0   Amit  25.0   Delhi
1  Rohit   NaN  Mumbai
2  Sneha  22.0    None
3  Priya   NaN    Pune
Cleaned:
     Name   Age     City
0   Amit  25.0    Delhi
1  Rohit  23.5   Mumbai
2  Sneha  22.0  Unknown
3  Priya  23.5     Pune
